#!/bin/sh
if test "z$*" = zversion ||
   test "z$*" = z--version
then
	echo 'git-gui version 0.21.0.93.g7b0cfe1-dirty'
else
	libdir="${GIT_GUI_LIB_DIR:-/Users/wbond/Desktop/git-build/build/env/share/git-gui/lib}"
	exec "$libdir/Git Gui.app/Contents/MacOS/Wish" "$0" "$@"
fi
